# 禁止Actuator监控Redis连接
management:
  health:
    redis:
      enabled: false

spring:
  profiles:
    active: dev

  servlet:
    session:
      timeout: 60  #session 超时时间为60秒
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

mybatis-plus:
  global-config:
      db-config:
        logic-delete-field: flag  # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
        logic-delete-value: 1 # 逻辑已删除值(默认为 1)
        logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)

  mapper-locations: classpath:Mybatis-plus/*.xml


#  控制台打印sql   需要时开启
#
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl