server:
  port: 8206
  servlet:
    session:
      timeout: 30
  tomcat:
    url-encoding: UTF-8
myenvironment:
  name: 生产环境

spring:
  messages:
    basename: login
  datasource:
    url: jdbc:sqlserver://localhost:1433;DatabaseName=LBB
    username: sa
    password: 123456
    initialSize: 5
    maxActive: 10
    maxWait: 3000
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    dype: com.alibaba.druid.pool.DruidDataSource
    druid:
      filters: stat,wall
      stat-view-servlet:
        enabled: true
        login-username: hwxadmin
        login-password: hwx001125
      web-stat-filter:
        enabled: true
        urlpattern: /*
        exclusions: '*.js,*.jgp,*.png,*.gif,*.css,*.ico,/druid/*'
      filter:
        slow-sql-millis: 1000
        logslowsql: true
        enabled: true
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
